# Nombre del proyecto dbt
# Debe estar en minúsculas y usar guiones bajos si es necesario
# Idealmente representa el objetivo del proyecto o la organización
name: "pyspark_dbt_medallion"
# Versión del proyecto (útil para control de cambios)
version: "1.0.0"

# Versión del esquema de configuración de dbt
config-version: 2

# Perfil de conexión que dbt usará (definido en profiles.yml)
# Este perfil indica cómo conectarse a Databricks
profile: "pyspark_dbt_medallion"

# Rutas donde dbt buscará los distintos tipos de archivos
model-paths: ["models"]        # Modelos SQL principales
analysis-paths: ["analyses"]   # Análisis exploratorios
test-paths: ["tests"]          # Tests de calidad de datos
seed-paths: ["seeds"]          # Archivos CSV cargados como tablas
macro-paths: ["macros"]        # Macros reutilizables
snapshot-paths: ["snapshots"]  # Snapshots para historización

# Carpeta donde dbt guarda archivos compilados
target-path: "target"

# Carpetas que se eliminan cuando se ejecuta `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# -------------------------
# CONFIGURACIÓN DE MODELOS
# -------------------------
# Aquí se define cómo se materializan los modelos (vista, tabla, incremental, etc.)
# También se puede controlar el schema de salida

models:
  pyspark_dbt_medallion:

    # Modelos de la capa SILVER
    # Transformaciones limpias y estructuradas desde Bronze
    silver:
      +materialized: table   # Se crean como tablas físicas
      +schema: silver        # Se guardan en el schema "silver"

    # Modelos de la capa GOLD
    # Datos finales listos para consumo analítico
    gold:
      +materialized: table   # Se crean como tablas físicas